meta:
  version: 3
  flow: Chip
  substituting_steps:
    Checker.IllegalOverlap: null
    KLayout.DRC: null
    Checker.KLayoutDRC: null
    Magic.DRC: null
    Checker.MagicDRC: null
    KLayout.SealRing: null
    KLayout.Antenna: null
    KLayout.Filler: null
    KLayout.Density: null
    Checker.KLayoutDensity: null
    Checker.KLayoutAntenna: null
    Magic.SpiceExtraction: null
    Netgen.LVS: null
    Checker.LVS: null

DESIGN_NAME: top

VERILOG_FILES:
  - src/top.v

CLOCK_PORT: io_clock_PAD
CLOCK_PERIOD: 10

FP_SIZING: absolute
DIE_AREA: [0, 0, 1200, 1200]
CORE_AREA: [358.0, 358.0, 842, 842]

PDN_CORE_RING: true
PDN_CORE_RING_CONNECT_TO_PADS: true
MAGIC_EXT_UNIQUE: notopports

PDN_ENABLE_PINS: false

PDN_CORE_RING_VWIDTH: 15
PDN_CORE_RING_HWIDTH: 15

PDN_VPITCH: 50
PDN_HPITCH: 50

PDN_VWIDTH: 3.5
PDN_HWIDTH: 3.5

PRIMARY_GDSII_STREAMOUT_TOOL: klayout

EXTRA_GDS: dir::bondpad/bondpad_70x70.gds
EXTRA_LEFS: dir::bondpad/bondpad_70x70.lef

PAD_WEST:
  - sg13g2_IOPad_io_clock
  - sg13g2_IOPad_io_reset
  - "sg13g2_IOPadOut30mA_uo\\[12\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[13\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[14\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[15\\].uo"

PAD_SOUTH:
  - "vdd_pads\\[0\\].vdd_pad"
  - "vss_pads\\[0\\].vss_pad"
  - "iovdd_pads\\[0\\].iovdd_pad"
  - "iovss_pads\\[0\\].iovss_pad"

PAD_EAST:
  - "sg13g2_IOPadOut30mA_uo\\[0\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[1\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[2\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[3\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[4\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[5\\].uo"

PAD_NORTH:
  - "sg13g2_IOPadOut30mA_uo\\[6\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[7\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[8\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[9\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[10\\].uo"
  - "sg13g2_IOPadOut30mA_uo\\[11\\].uo"

VDD_NETS:
  - VDD

GND_NETS:
  - VSS

GRT_ALLOW_CONGESTION: true

IGNORE_DISCONNECTED_MODULES:
  - bondpad_70x70

MACROS:
  counter_8bit:
    gds: dir::ip/final/gds/counter_8bit.gds
    lef: dir::ip/final/lef/counter_8bit.lef
    nl: dir::ip/final/pnl/counter_8bit.pnl.v
    lib:
      nom_typ_1p20V_25C: dir::ip/final/lib/nom_typ_1p20V_25C/counter_8bit__nom_typ_1p20V_25C.lib
      nom_fast_1p32V_m40C: dir::ip/final/lib/nom_fast_1p32V_m40C/counter_8bit__nom_fast_1p32V_m40C.lib
      nom_slow_1p08V_125C: dir::ip/final/lib/nom_slow_1p08V_125C/counter_8bit__nom_slow_1p08V_125C.lib
    spef:
      nom_typ_1p20V_25C: dir::ip/final/spef/nom/counter_8bit.nom.spef
    instances:
      u_counter_8bit_1:
        location: [640, 630]
        orientation: N
      u_counter_8bit_0:
        location: [440, 430]
        orientation: N

PDN_MACRO_CONNECTIONS:
  - u_counter_8bit_0 VDD VSS VPWR VGND
  - u_counter_8bit_1 VDD VSS VPWR VGND
